version: "3.9"
services:
  nginx:
    ports:
      - 3000:80

  url-shortener:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes: 
      - ./:/app # bind mount vol, DX++
      - /app/node_modules # hack to prevent overriding packages using anonymous vol
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/upgraded-spoon
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=xyz
    command: npm run dev
