version: "3.9"
services:
  url-shortener:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/upgraded-spoon
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=abc
    command: node src/index.js
